name: Android Debug APK

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - 'buildozer.spec'
      - '.github/workflows/android-debug.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_BUILDKIT: 0
      COMPOSE_DOCKER_CLI_BUILD: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Buildozer and Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.gradle
          key: ${{ runner.os }}-p4a-${{ hashFiles('buildozer.spec') }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip libstdc++6 zlib1g-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel cython
          python -m pip install buildozer==1.5.0

      - name: Build debug APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: bin/*-debug.apk
          if-no-files-found: error
          retention-days: 7

      - name: Always upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            buildozer.log
            .buildozer/**/*.log
            .buildozer/**/logs/**
            bin/*-debug.apk
          if-no-files-found: ignore
          retention-days: 7
